<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\BlogCategory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class BlogCategoryController extends Controller
{
    /**
     * Display category list with create/edit modals.
     */
    public function index(): View
    {
        $categories = BlogCategory::withCount('posts')
            ->orderBy('name')
            ->paginate(20);

        return view('admin.blog.categories.index', compact('categories'));
    }

    /**
     * Store a newly created category.
     * Slug is auto-generated by the model's booted() saving hook.
     */
    public function store(Request $request): RedirectResponse
    {
        $validated = $this->validateRequest($request);

        BlogCategory::create([
            'name' => $validated['name'],
            // slug auto-generated via booted() saving hook in BlogCategory model
        ]);

        return redirect()
            ->route('admin.blog-categories.index')
            ->with('success', 'Category created.');
    }

    /**
     * Update the specified category.
     * Only name is updated. Slug stays locked once created (URL stability).
     */
    public function update(Request $request, BlogCategory $blogCategory): RedirectResponse
    {
        $validated = $this->validateRequest($request);

        $blogCategory->update([
            'name' => $validated['name'],
            // Slug intentionally NOT updated. Once a slug is set, it stays — preserves URLs.
        ]);

        return redirect()
            ->route('admin.blog-categories.index')
            ->with('success', 'Category updated.');
    }

    /**
     * Soft-delete the specified category.
     * Blocks if category still has attached posts.
     */
    public function destroy(BlogCategory $blogCategory): RedirectResponse
    {
        $postsCount = $blogCategory->posts()->count();

        if ($postsCount > 0) {
            return redirect()
                ->route('admin.blog-categories.index')
                ->with('error', "Cannot delete: category is still attached to {$postsCount} post(s). Detach posts first.");
        }

        $blogCategory->delete();

        return redirect()
            ->route('admin.blog-categories.index')
            ->with('success', 'Category deleted.');
    }

    /**
     * Shared validation rules for store + update.
     */
    private function validateRequest(Request $request): array
    {
        return $request->validate([
            'name' => 'required|string|max:100',
        ]);
    }
}